@isTest
public class DeploymentHelperTest{

    static testMethod void t1(){
        DeploymentHelper dd = new DeploymentHelper();
        dd.method1();
        dd.method2();
        dd.method3();
        dd.method4();
        dd.method5();
        dd.method6();
        dd.method7();
        dd.method8();
        dd.method9();
        dd.method10();
        dd.method11();
        dd.method12();
        dd.method13();
        dd.method14();
        dd.method15();
        dd.method16();
        dd.method17();
        dd.method18();
        dd.method19();
        dd.method20();
        dd.method21();
        dd.method22();
        dd.method23();
        dd.method24();
        dd.method25();
        dd.method26();
        dd.method27();
        dd.method28();
        dd.method29();
        dd.method30();
    }
}